### ISSUE TITLE
Cards load but stuck "Loading...." with certain elements.

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#1292]
Since upgrading from 9.4 to 9.5, certain bot cards don't load.

We see "Loading...." in the header but then you cannot click on anything in the card. Due to this, we cannot determine which element on the card is causing this as others do work when you reload the page.

The card in question attached.
<img width="423" alt="Screenshot 2020-05-07 at 1 55 27 AM" src="https://user-images.githubusercontent.com/15971590/81242827-0c5f5800-9006-11ea-858c-079098120c00.png">

**Comment by iammattmartin** [comment]
This error appears in the console when it happens.

```
TypeError: e.stopPropagation is not a functionjquery.combined.min.js:3:4
    jQuery 14
    callback https://hd.custserv.net/resource/devblocks.core/js/devblocks.js?v=2020043001:1313
    jQuery 4
```

**Comment by jstanden** [comment]
Hi Matt!

I haven't seen any other reports for this.

I'll research the stack trace. Do you have any other changes in `git status` than the config file and install dir?

**Comment by iammattmartin** [comment]
None that we've changed. Apart from install/....

```
	modified:   vendor/defuse/php-encryption/bin/generate-defuse-key
	modified:   vendor/paragonie/random_compat/build-phar.sh
	modified:   features/cerberusweb.core/resources/css/input_icons/add.png
	modified:   features/cerberusweb.core/resources/css/input_icons/colors.png
	modified:   features/cerberusweb.core/resources/css/input_icons/date.png
	modified:   features/cerberusweb.core/resources/css/input_icons/forbidden.png
	modified:   features/cerberusweb.core/resources/css/input_icons/link.png
	modified:   features/cerberusweb.core/resources/css/input_icons/location.png
	modified:   features/cerberusweb.core/resources/css/input_icons/lock.png
	modified:   features/cerberusweb.core/resources/css/input_icons/mail.png
	modified:   features/cerberusweb.core/resources/css/input_icons/phone.png
	modified:   features/cerberusweb.core/resources/css/input_icons/tag.png
	modified:   features/cerberusweb.core/resources/css/input_icons/time.png
	modified:   features/cerberusweb.core/resources/css/input_icons/url.png
	modified:   framework.config.php
```

**Comment by jstanden** [comment]
k! Thanks. I'm assuming it's the template for one of those actions in the screenshot. I'm setting up a test now that emulates it.

**Comment by iammattmartin** [comment]
Let me know if I can do any other tests.

**Comment by jstanden** [comment]
I couldn't reproduce it in the current dev, but I can reproduce it in 9.5.4.

It's resolved in this patch (already in 9.6, but needs backported to 9.5.x):

~~~
diff --git a/features/cerberusweb.core/templates/events/action_set_placeholder_using_snippet.tpl b/features/cerberusweb.core/templates/events/action_set_placeholder_using_snippet.tpl
index 5ed61a329..b535017a5 100644
--- a/features/cerberusweb.core/templates/events/action_set_placeholder_using_snippet.tpl
+++ b/features/cerberusweb.core/templates/events/action_set_placeholder_using_snippet.tpl
@@ -40,9 +40,7 @@
 </div>
 
 <script type="text/javascript">
-$(function(e) {
-       e.stopPropagation();
-
+$(function() {
        var $action = $('#{$namePrefix}_{$nonce}');
        var $snippet_preview = $action.find('div.snippet-preview');
        
~~~

I'll get that merged into cerb/cerb-release.

**Comment by iammattmartin** [comment]
Can confirm that fixed it.

**Comment by jstanden** [comment]
Great! Thanks. I'm merging that in now.

**Comment by jstanden** [comment]
Fixed in 9.5.6 and pushed to cerb/cerb-release
